SELECT CURRENT_USER();
SELECT CURRENT_ROLE();
SELECT CURRENT_WAREHOUSE();
SELECT CURRENT_DATABASE();
SELECT CURRENT_SCHEMA();


CREATE OR REPLACE DATABASE CAMPUS_DB;

USE DATABASE CAMPUS_DB;

CREATE OR REPLACE SCHEMA TRAINING_SCHEMA;

USE SCHEMA TRAINING_SCHEMA;

CREATE OR REPLACE WAREHOUSE TRAINING_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE TRAINING_WH;


CREATE OR REPLACE TABLE STUDENT_DETAILS (
    ID INT,
    STUDENT_NAME STRING,
    COURSE STRING,
    SCORE INT
);

CREATE OR REPLACE STAGE TRAINING_STAGE;


SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;
SHOW TABLES;
SHOW STAGES;


INSERT INTO STUDENT_DETAILS VALUES
(301, 'Rohan', 'BCA', 81),
(302, 'Sneha', 'BBA', 89),
(303, 'Aditya', 'MCA', 77);

SELECT * FROM STUDENT_DETAILS;


UPDATE STUDENT_DETAILS
SET SCORE = 93
WHERE ID = 302;

SELECT * FROM STUDENT_DETAILS;


DELETE FROM STUDENT_DETAILS
WHERE ID = 303;

SELECT * FROM STUDENT_DETAILS;


CREATE OR REPLACE TABLE EXAM_RESULTS (
    GENDER STRING,
    RACE_ETHNICITY STRING,
    PARENTAL_LEVEL_OF_EDUCATION STRING,
    LUNCH STRING,
    TEST_PREPARATION_COURSE STRING,
    MATH_SCORE INT,
    READING_SCORE INT,
    WRITING_SCORE INT
);

LIST @TRAINING_STAGE;


CREATE OR REPLACE FILE FORMAT RESULTS_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


COPY INTO EXAM_RESULTS
FROM @TRAINING_STAGE/StudentsPerformance.csv
FILE_FORMAT = RESULTS_CSV_FORMAT;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM EXAM_RESULTS;

SELECT *
FROM EXAM_RESULTS
LIMIT 10;


CREATE OR REPLACE TABLE EMPLOYEE_DETAILS (
    EMPLOYEE_ID INT,
    EMPLOYEE_NAME STRING,
    SALARY INT
);

INSERT INTO EMPLOYEE_DETAILS VALUES
(11, 'Nikhil', 48000),
(12, 'Kavya', 55000),
(13, 'Manish', 62000);

SELECT * FROM EMPLOYEE_DETAILS;


UPDATE EMPLOYEE_DETAILS
SET SALARY = 68000
WHERE EMPLOYEE_ID = 11;

DELETE FROM EMPLOYEE_DETAILS
WHERE EMPLOYEE_ID = 13;

SELECT * FROM EMPLOYEE_DETAILS;


SELECT *
FROM EMPLOYEE_DETAILS
AT(OFFSET => -60);


INSERT INTO EMPLOYEE_DETAILS
SELECT *
FROM EMPLOYEE_DETAILS
AT(OFFSET => -60)
WHERE EMPLOYEE_ID = 13;

SELECT * FROM EMPLOYEE_DETAILS;
